arch: ResNet50
aug: true
batch_size: 512
ckpt: ''
color_dist_s: 1.0
config_file: ''
data: imagenet
dist: ddp
dist_address: '127.0.0.1:12344'
eval_freq: 50040
gpu: 0
iters: 250200
log_freq: 100
lr: 0.6
lr_schedule: warmup-anneal
multiplier: 2
name: imagenet-512-simclr-mobius
mobus: true
mobius-prob: 0.8
mobius_background: true
node_rank: 0
opt: lars
problem: sim-clr
root: '/'
save_freq: 12510
scale_lower: 0.08
seed: -1
sync_bn: true
temperature: 0.1
tmp: false
verbose: true
warmup: 0.1
weight_decay: 1.0e-06
workers: 4
world_size: 1
